version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build:
      context: ../../
      args:
        NODE_ENV: production
    image: imsamad/node-app
    env_file: ../../.env
    # environment:
    #   - NODE_ENV=development
    #   # - MONGO_USER=sanjeev
    #   - MONGO_USER=${MONGO_USER}
    #   # - MONGO_PASSWORD=mypassword
    #   - MONGO_PASSWORD=${MONGO_PASSWORD}
    #   # - SESSION_SECRET=secret
    #   - SESSION_SECRET=${SESSION_SECRET}
    #   - PORT=3000
    command: node index.js
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file: ../../.env
    # environment:
    #   # - MONGO_INITDB_ROOT_USERNAME=sanjeev
    #   # - MONGO_INITDB_ROOT_PASSWORD=mypassword
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
