version: '3'
services:
  server:
    build:
      context: ../../app/server
      args:
        NODE_ENV: production
    image: imsamad/ecart_api
    env_file: ../../app/server/.env
    depends_on:
      - mongo
      - client
      - redis

  client:
    build:
      context: ../../app/client
    env_file:
      - ../../app/client/.env
    image: imsamad/ecart_client

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server

  mongo:
    image: mongo
    env_file: ../../app/server/.env
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
