version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3000:80'
    env_file: ../../.env
    volumes:
      - ../../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build:
      context: ../../
      args:
        NODE_ENV: development
    volumes:
      - ../../:/app
      - apiModules:/app/node_modules
    image: sloppynetworks/node-app
    env_file: ../../.env
    # environment:
    #   - PORT=3000
    #   - NODE_ENV=development
    #   - MONGO_USER=sanjeev
    #   - MONGO_PASSWORD=mypassword
    #   - SESSION_SECRET=secret
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file: ../../.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=sanjeev
    #   - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
  apiModules:
